### ISSUE TITLE
Allow Disk II cards in slots besides S6

### ISSUE THREAD

**Issue by munsie** [a2-4am/passport#111]
It would be very useful to be able to use Passport with a Disk II card in a different slot than S6.  In my use case, I have an Apple IIe with a Yellowstone card in S6 connected to a Floppy Emu in SmartPort mode.  I have a Disk II card in S5 connected to a 5.25" drive.  I would like to be able to run Passport off the Floppy Emu hard drive image and use it to create disk images from the 5.25" drive.

Today when starting up Passport from the Floppy Emu hard drive image in this config, it says "Passport requires a Disk II drive in S6.  Press any key to quit"

I was previously able to use this same hard drive image and Floppy Emu with an Apple IIc and it's internal 5.25" drive.

**Comment by munsie** [comment]
Upon further reflection, I realize there may be an issue with getting some of Passport’s functionality  working on other slots due to using custom RWTS implementations. In my own use case, I think I can simply shift up my to cards to be in S6 and S7. I will leave this issue open in case there is a possibility of some functionality without a Disk II card in S6.

**Comment by peterferrie** [comment]
Many titles hard-code their disk accesses to slot 6, so we can't change the source because in many cases we are using the
original disk's actual RWTS routines.
