### ISSUE TITLE
Cannot switch between S6,D1 and S6,D2 

### ISSUE THREAD

**Issue by mldma** [a2-4am/passport#112]
In applewin, when the "s" key is pressed, there is no response on the screen

**Comment by xotmatrix** [comment]
"S" advances the slot and drive of the target but I believe the source is always S6,D1, so it cannot be selected. If there is only one disk controller, there will be no change. If a disk controller is inserted into slot 5 of AppleWin, the "S" key will be shown to work. 

See `slot.a` which handles advancing the target. It looks like the code at line 63 is to prevent S6,D1 from being selected.

**Comment by peterferrie** [comment]
> "S" advances the slot and drive of the target but I believe the source is
> always S6,D1, so it cannot be selected.

Correct.  Many titles hard-code their disk accesses to slot 6, so we
can't change the source because in many cases we are using the
original disk's actual RWTS routines.
Only the target can be changed.

**Comment by mldma** [comment]
The situation is as follows: an apple II compatible computer (with build-in slot6 disk drive interface),  a DSK-emul drive (S6, D2), 
and a DISK II drive (S6, D1). My purpose is to test copying  encrypted floppy disk (S6, D1) to  DSK-emu (S6, D2) .
Transfer passport.dsk to a real floppy disk, it can only be booted into ProDOS(s6,d1) and halting,  say  passport.system is inaccessible. (Applewin can) .
Swap DSK-emu to D6,D1 DISKII to d2, disk boot is ok .but since the default setting cannot be adjusted, encrypted floppy disk(S6, D2) can't be read and copied. It is recommended to make copy direction selectable A-B or B-A ,like copy ][ plus .

**Comment by peterferrie** [comment]
> The situation is as follows: an apple II compatible computer (with build-in
> slot6 disk drive interface),  a DSK-emul drive (S6, D2),
> and a DISK II drive (S6, D1). My purpose is to test copying  encrypted
> floppy disk (S6, D1) to  DSK-emu (S6, D2) .
> Transfer passport.dsk to a real floppy disk, it can only be booted into
> ProDOS(s6,d1) and halting,  say  passport.system is inaccessible. (Applewin
> can) .

Try booting another ProDOS disk to reach a Basic prompt, with Passport
in drive 2.
Passport can be launched from the prompt, via "-passport.system,d2".

> Swap DSK-emu to D6,D1 DISKII to d2, disk boot is ok .but since the default
> setting cannot be adjusted, encrypted floppy disk(S6, D2) can't be read and
> copied. It is recommended to make copy direction selectable A-B or B-A ,like
> copy ][ plus .

Again, we do not control how copy-protected disks access the drive
that they use.  To swap the source drive could break many things,
including accidental overwrite of your original disk.

**Comment by mldma** [comment]
That's it, thank you
